<?php
/**
 *autobase default Store switch languages template.
 *@author Ivan Havryliuk ivan.havryliuk95@gmail.com.
 *@copyright 2020 worzewolf.
 */

/** @var \Magento\Store\Block\Switcher $block */
?>
<?php if (count($block->getStores())>1) : ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
        <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Language')) ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true">
                <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                    <span><?= $block->escapeHtml($block->getStoreName()) ?></span>
                </strong>
            </div>
            <?php foreach ($block->getStores() as $_lang) : ?>
                <?php if ($_lang->getId() != $block->getCurrentStoreId()) : ?>
                    <span class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option">
                            <a href="<?= $block->escapeUrl($block->getViewModel()->getTargetStoreRedirectUrl($_lang)) ?>">
                                <?= $block->escapeHtml($_lang->getName()) ?>
                            </a>
                        </span>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
