<?php
/**
 *autobase module Expand product view attributes template.
 *@author Ivan Havryliuk ivan.havryliuk95@gmail.com.
 *@copyright 2020 worzewolf.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()) : ?>
    <div class="additional-attributes-wrapper table-wrapper parent-expand-container" id="product-attribute-specs-table">
        <h3 class="desc-title"><?= __('Product specifications') ?></h3>
        <div class="product expand-container">
            <table class="data additional-attributes">
                <?php foreach ($_additional as $_data) : ?>
                    <tr class="attribute">
                        <th class="col label" scope="row"><?= $block->escapeHtml($_data['label']) ?></th>
                        <td class="col data" data-th="<?= $block->escapeHtmlAttr($_data['label']) ?>">
                            <?= /* @noEscape */
                            $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
        <div class="expand-button-container">
            <span class="expand_button hide"><?= __('Hide') ?></span>
            <span class="expand_button show active"><?= __('Show all characteristics') ?></span>
        </div>
    </div>
<?php endif; ?>
<div class="product description">
    <h3 class="title-description"><?= __('Description products') ?></h3>
    <div class="expand-container-description">
        <div class="short-description">
            <?php echo $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'short_description') ?>
        </div>
        <div class="expand-button-container">
            <span class="expand_button-description hide"><?= __('Hide') ?></span>
            <span class="expand_button-description show"><?= __('More info') ?></span>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".expand-container": {
            "autobase_Expand/js/expand-service": {
                            "parentElem": ".parent-expand-container",
                            "expandContainer": ".expand-container",
                            "expandButtonShow": ".expand_button.show",
                            "expandButtonHide": ".expand_button.hide"
            }
        },
        ".expand-container-description": {
            "autobase_Expand/js/expand-service": {
                            "parentElem": ".expand-container-description",
                            "expandContainer": ".short-description",
                            "expandButtonShow": ".expand_button-description.show",
                            "expandButtonHide": ".expand_button-description.hide"
            }
        }
    }
</script>
