<?php
/**
 *autobase module Expand product view list template.
 *@author Ivan Havryliuk ivan.havryliuk95@gmail.com.
 *@copyright 2020 worzewolf.
 */

/** @var Magento\Review\Block\Product\View\ListView $block */

$_items = $block->getReviewsCollection()->getItems();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>

<?php if (count($_items)) : ?>
<div class="block review-list" id="customer-reviews">
    <?php if (!$block->getHideTitle()) : ?>
        <div class="block-title">
            <strong><?= $block->escapeHtml(__('Customer Reviews')) ?></strong>
        </div>
    <?php endif ?>
    <div class="block-content">
        <div class="toolbar review-toolbar">
            <?= $block->getChildHtml('toolbar') ?>
        </div>
        <ol class="items review-items">
        <?php foreach ($_items as $_review) : ?>
            <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review">
                <div class="review-wrap">
                    <div class="review-details">
                        <p class="review-author">
                            <strong class="review-details-value" itemprop="author"><?= $block->escapeHtml($_review->getNickname()) ?></strong>
                        </p>
                        <p class="review-date">
                            <time class="review-details-value" itemprop="datePublished" datetime="<?= $block->escapeHtmlAttr($block->formatDate($_review->getCreatedAt(), $format)) ?>"><?= $block->escapeHtml($block->formatDate($_review->getCreatedAt(), $format)) ?></time>
                        </p>
                    </div>
                    <div class="review-content" itemprop="description">
                        <?= /* @noEscape */ nl2br($block->escapeHtml($_review->getDetail())) ?>
                    </div>
                    <div class="review pros-cons" itemprop="name"><p><span class="pros"><?= __('Advantages') ?></span><?= $block->escapeHtml($_review->getTitle()) ?></p></div>
                    <div class="review pros-cons" itemprop="name"><p><span class="cons"><?= __('Disadvantages') ?></span><?= __('not found') ?></p></div>
                    <div class="review-customers-reaction">
                        <div class="answer-review">
                            <a href="#">1 <?= __('Answer') ?></a>
                            <a href="#"><?= __('Respond') ?></a>
                        </div>
                        <div class="community-reaction" data-bind="scope: 'simpleComponent'">
                            <span class="reaction-label"><?= __('Was this review helpful to you:') ?></span>
                            <span class="review-like-button"><span class="like" data-bind="click: plusRate, text: votefor">14</span></span>
                            <span class="review-dislike-button"><span class="dislike" data-bind="click: minusRate, text: voteagainst">3</span></span>
                        </div>
                    </div>
                </div>
                <?php if (count($_review->getRatingVotes())) : ?>
                    <div class="review-ratings">
                        <?php foreach ($_review->getRatingVotes() as $_vote) : ?>
                            <div class="rating-summary item" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                                <div class="label rating-label"><span><?= $block->escapeHtml($_vote->getRatingCode()) ?></span></div>
                                <div class="rating-result" title="<?= $block->escapeHtmlAttr($_vote->getPercent()) ?>%">
                                    <meta itemprop="worstRating" content = "1"/>
                                    <meta itemprop="bestRating" content = "100"/>
                                    <span style="width:<?= $block->escapeHtmlAttr($_vote->getPercent()) ?>%">
                                                <span itemprop="ratingValue"><?= $block->escapeHtml($_vote->getPercent()/20) ?>,0</span>
                                            </span>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ol>
        <div class="toolbar review-toolbar">
            <span class="show-details"><?= __('Show all reviews') ?></span>
            <?= $block->getChildHtml('toolbar') ?>
        </div>
    </div>
</div>
<?php endif;?>
